import type { Grant, Milestone } from "../../lib/domain";
import { ExplorerLink } from "./grant-overview";

const date = (seconds: bigint) => seconds === 0n ? "Not recorded by the contract" : new Date(Number(seconds) * 1_000).toLocaleString();
export function EvidencePanel({ grant, milestone }: { grant: Grant; milestone: Milestone }) {
  const submissions = Number(milestone.submissionNonce);
  const challenges = Number(milestone.challengeNonce);
  return <section className="evidence-panel"><h2>Evidence and provenance</h2><p>Evidence is publicly committed by hash. Source details that are not stored on-chain are explicitly marked instead of inferred.</p><dl className="provenance-grid"><div><dt>Evidence pack hash</dt><dd><code>{milestone.evidencePackHash || "No evidence pack"}</code> {milestone.evidencePackHash && <ExplorerLink value={milestone.evidencePackHash} label="Explorer" />}</dd></div><div><dt>Issuer</dt><dd>Not recorded by the contract</dd></div><div><dt>Subject</dt><dd>{grant.projectName} · milestone {Number(milestone.index) + 1}</dd></div><div><dt>Policy version</dt><dd>{grant.evidencePolicyVersion}</dd></div><div><dt>Source dates</dt><dd>Milestone deadline: {date(milestone.deadline)}</dd></div><div><dt>Consensus rationale</dt><dd>Derived by the contract’s configured evidence policy; rationale text is not returned by this public read.</dd></div></dl><h3>Historical submissions and challenges</h3><ul className="history-list">{submissions ? Array.from({ length: submissions }, (_, index) => <li key={`submission-${index}`}>Evidence submission #{index + 1}{index + 1 === submissions ? `: ${milestone.evidencePackHash || "hash not available"}` : ": historic pack hash is not returned by this read"}.</li>) : <li>No evidence submission has been recorded.</li>}{challenges ? Array.from({ length: challenges }, (_, index) => <li key={`challenge-${index}`}>Challenge #{index + 1}; public counter-evidence hash is not returned by this read.</li>) : <li>No challenge has been recorded.</li>}</ul><p className="challenge-countdown">Challenge deadline: {date(milestone.challengeDeadline)}</p></section>;
}
