import Link from "next/link";
import Image from "next/image";

import type { Grant, Milestone, MilestoneStatus } from "../../lib/domain";

const artwork: Record<string, string> = { Water: "water", Climate: "climate", Health: "health" };
const label: Record<Grant["status"], string> = { FUNDING: "Funding open", ACTIVE: "Milestones active", COMPLETED: "Contract complete", EXPIRED: "Contract expired" };
const milestoneLabel: Partial<Record<MilestoneStatus, string>> = { PENDING: "Awaiting evidence", REQUEST_MORE_INFO: "More information requested", CHALLENGED: "Decision challenged", PAID: "Payout complete", REFUNDED: "Escrow refunded" };
const gen = (amount: bigint) => `${new Intl.NumberFormat("en-US").format(amount)} GEN`;

export function GrantCard({ grant, milestones = [] }: { grant: Grant; milestones?: Milestone[] }) { const paid = milestones.filter((milestone) => milestone.status === "PAID").length; const target = grant.escrowTarget || 1n; const percent = Math.min(100, Number((grant.funded * 100n) / target)); const stateDetail = milestones.find((milestone) => milestone.status !== "PAID")?.status; return <article className={`grant-card grant-card--${artwork[grant.category] ?? "community"}`}><div className="grant-card__image"><Image alt={`${grant.projectName} project landscape`} fill sizes="(max-width: 620px) 100vw, (max-width: 900px) 50vw, 33vw" src="/assets/project-mosaic.svg" /><span className="image-tag">{grant.category}</span><span className="image-shape" aria-hidden="true" /></div><div className="grant-card__body"><div className="card-meta"><span>{grant.region}</span><span className={`status status--${grant.status.toLowerCase()}`}><i />{label[grant.status]}</span></div><h3><Link href={`/grant/${grant.grantId}`} aria-label={`Explore ${grant.projectName}`}>{grant.projectName}</Link></h3><p className="organization">{grant.organization}</p><p className="card-description">{grant.description}</p><div className="funding-row"><strong>{gen(grant.funded)}</strong><span>of {gen(grant.escrowTarget)}</span></div><div className="progress" aria-label={`${percent}% funded`}><span style={{ width: `${percent}%` }} /></div><div className="card-proof"><span><b>{paid}</b> of {grant.milestoneCount.toString()} milestones paid</span><span className="proof-state">{stateDetail ? milestoneLabel[stateDetail] ?? stateDetail.replaceAll("_", " ") : "Milestone plan locked"}</span></div><div className="card-footer"><span>Simulated Studionet value</span><Link href={`/grant/${grant.grantId}`} aria-label={`Explore ${grant.projectName}`}>Follow trail <span aria-hidden="true">→</span></Link></div></div></article>; }
