"use client";

import Link from "next/link";

import type { Grant, Milestone, Summary } from "../../lib/domain";
import { useWallet } from "../providers/wallet-provider";
import { CreditForm } from "../forms/credit-form";

export type DashboardMode = "ready" | "loading" | "empty" | "read-error";
export function DashboardClient({ grants, milestones, summary, credit = 0n, mode }: { grants: Grant[]; milestones: Milestone[]; summary?: Summary; credit?: bigint; mode: DashboardMode }) {
  const wallet = useWallet();
  if (mode === "loading") return <main className="dashboard"><div className="skeleton dashboard-skeleton" /><div className="skeleton dashboard-skeleton" /></main>;
  if (mode === "read-error") return <main className="dashboard"><section className="empty-state"><p className="eyebrow">Contract read unavailable</p><h1>Your reconciliation view is waiting.</h1><p>The public network read could not be confirmed. Retry when Studionet is available; no balances are inferred locally.</p><Link className="button" href="/dashboard">Retry read</Link></section></main>;
  if (wallet.status === "wrong_network") return <main className="dashboard"><section className="empty-state"><p className="eyebrow">Wrong network</p><h1>Switch to Studionet.</h1><p>Workflow actions remain protected until the selected wallet is on the configured AidTrail network.</p></section></main>;
  if (mode === "empty") return <main className="dashboard"><section className="empty-state"><p className="eyebrow">Your role dashboard</p><h1>No contract responsibilities yet.</h1><p>Sponsor a transparent grant or connect the wallet assigned to a beneficiary task.</p><Link className="button" href="/grants/new">Create a grant</Link></section></main>;
  const owned = grants.filter((grant) => wallet.account && (grant.sponsor.toLowerCase() === wallet.account.toLowerCase() || grant.beneficiary.toLowerCase() === wallet.account.toLowerCase())); const deadline = milestones.filter((milestone) => milestone.status.startsWith("PROVISIONAL") || milestone.status === "PENDING");
  const sponsored = owned.filter((grant) => wallet.account && grant.sponsor.toLowerCase() === wallet.account.toLowerCase()); const tasks = deadline.filter((milestone) => owned.some((grant) => grant.grantId === milestone.grantId)); const challenges = deadline.filter((milestone) => milestone.challengeDeadline > 0n);
  return <main className="dashboard"><header className="dashboard-heading"><p className="eyebrow">Your contract responsibilities</p><h1>Follow every promise through its consequence.</h1><p>Recoverable credits and deadlines only become final after contract execution and readback.</p></header><div className="dashboard-grid"><section className="dashboard-panel"><h2>Sponsored grants</h2>{sponsored.length ? sponsored.map((grant) => <Link className="dashboard-row" href={`/grant/${grant.grantId}`} key={grant.grantId}><span>{grant.projectName}</span><small>{grant.funded.toString()} / {grant.escrowTarget.toString()} GEN · {grant.status}</small></Link>) : <p>None from this wallet.</p>}</section><section className="dashboard-panel"><h2>Beneficiary tasks</h2>{tasks.length ? tasks.map((milestone) => <Link className="dashboard-row" href={`/grant/${milestone.grantId}`} key={`${milestone.grantId}-${milestone.index}`}><span>{milestone.title}</span><small>{milestone.status} · deadline {milestone.deadline.toString()}</small></Link>) : <p>No active evidence tasks.</p>}</section><section className="dashboard-panel"><h2>Provisional & challenge windows</h2>{challenges.length ? challenges.map((milestone) => <div className="dashboard-row" key={`challenge-${milestone.grantId}-${milestone.index}`}><span>{milestone.title}</span><small>Challenge closes {milestone.challengeDeadline.toString()}</small></div>) : <p>No open challenge windows.</p>}</section><CreditForm credit={credit} /></div>{summary && <section className="dashboard-panel dashboard-summary"><h2>Network reconciliation</h2><dl><div><dt>Reserved milestone escrow</dt><dd>{summary.reservedMilestoneEscrow.toString()} GEN</dd></div><div><dt>Available credits</dt><dd>{summary.availableCredits.toString()} GEN</dd></div><div><dt>Returned / slashed bonds</dt><dd>{summary.returnedBonds.toString()} / {summary.slashedBonds.toString()} GEN</dd></div></dl></section>}<aside className="dashboard-states"><strong>Transaction state guide:</strong> signature rejected, consensus timeout, execution error, and readback mismatch are recoverable states shown immediately after a submitted write; success is only shown after the contract state can be read back.</aside></main>;
}
