"use client";

import { useMemo, useState } from "react";

import type { Grant, Milestone } from "../../lib/domain";
import { createAidTrailContract } from "../../lib/genlayer/contract";
import { createWriteClient } from "../../lib/genlayer/write-client";
import { useTransaction, TransactionStatus } from "../providers/transaction-provider";
import { useWallet } from "../providers/wallet-provider";

const unix = () => Math.floor(Date.now() / 1000);
const artifact = (issuer: string, url: string, contentHash: string, subject: object) => ({ schema_version: 1, issuer, url, content_hash: contentHash, content_version: "v1", subject, dates: { observation_start: unix() - 86400, observation_end: unix() - 3600, published_at: unix() - 60 } });
export function EvidenceForm({ grant, milestone }: { grant: Grant; milestone: Milestone }) {
  const wallet = useWallet(); const transaction = useTransaction(); const [reportUrl, setReportUrl] = useState(""); const [reportHash, setReportHash] = useState(""); const [sourceUrl, setSourceUrl] = useState(""); const [sourceIssuer, setSourceIssuer] = useState(""); const [sourceHash, setSourceHash] = useState("");
  const pack = useMemo(() => { const subject = { project_name: grant.projectName, project_reference: grant.projectReference, region: grant.region, milestone_title: milestone.title, criteria_hash: milestone.criteriaHash }; return { schema_version: 1, action: "SUBMIT_EVIDENCE", network: "genlayer:configured-network", contract_replay_marker: "AIDTRAIL:EVIDENCE:V1:configured-contract", grant_id: grant.grantId, milestone_index: Number(milestone.index), submission_nonce: Number(milestone.submissionNonce + 1n), report: artifact(grant.beneficiary, reportUrl, reportHash, subject), independent_sources: sourceUrl ? [artifact(sourceIssuer, sourceUrl, sourceHash, subject)] : [] }; }, [grant, milestone, reportHash, reportUrl, sourceHash, sourceIssuer, sourceUrl]);
  const ready = /^https:\/\//.test(reportUrl) && /^0x[0-9a-fA-F]{64}$/.test(reportHash) && pack.independent_sources.length >= Number(milestone.minIndependentSources);
  const submit = async () => { if (!ready || wallet.status !== "connected" || !wallet.account || !wallet.provider) return; const client = await createWriteClient(wallet.provider, wallet.account); const contract = createAidTrailContract({ address: process.env.NEXT_PUBLIC_AIDTRAIL_CONTRACT_ADDRESS, writeClient: client }); await transaction.execute(() => contract.submitEvidence({ grantId: grant.grantId, milestoneIndex: milestone.index, evidenceJson: JSON.stringify(pack), readback: async () => true })); };
  return <section className="workflow-card"><p className="eyebrow">Beneficiary evidence</p><h2>Submit proof without an AidTrail upload.</h2><p>URLs and integrity hashes go directly to the contract. The canonical preview locks the evidence subject, freshness dates, nonce, and replay domain.</p><div className="form-grid"><label className="form-field"><span>Primary public report URL</span><input value={reportUrl} placeholder="https://…" onChange={(event) => setReportUrl(event.target.value)} /></label><label className="form-field"><span>Primary content hash</span><input value={reportHash} placeholder="0x…" onChange={(event) => setReportHash(event.target.value)} /></label><label className="form-field"><span>Independent source URL</span><input value={sourceUrl} placeholder="https://…" onChange={(event) => setSourceUrl(event.target.value)} /></label><label className="form-field"><span>Independent issuer</span><input value={sourceIssuer} onChange={(event) => setSourceIssuer(event.target.value)} /></label><label className="form-field form-field--wide"><span>Independent source content hash</span><input value={sourceHash} placeholder="0x…" onChange={(event) => setSourceHash(event.target.value)} /></label></div><details><summary>Canonical evidence pack preview</summary><pre>{JSON.stringify(pack, null, 2)}</pre></details><p className="form-hint">Freshness is checked at execution. Distinct issuers and hosts protect independent sources; replay markers bind this pack to AidTrail on the configured network.</p><button type="button" className="button" disabled={!ready || wallet.status !== "connected"} onClick={() => void submit()}>Sign evidence submission</button>{transaction.state.phase !== "awaiting_wallet" && <TransactionStatus state={transaction.state} />}</section>;
}
