"use client";

import { isAddress } from "viem";
import { useMemo, useState } from "react";

import type { Address } from "../../lib/domain";
import { createAidTrailContract } from "../../lib/genlayer/contract";
import { createWriteClient } from "../../lib/genlayer/write-client";
import { useTransaction, TransactionStatus } from "../providers/transaction-provider";
import { useWallet } from "../providers/wallet-provider";

export interface GrantPlanFields { beneficiary: string; projectName: string; organization: string; projectReference: string; region: string; category: string; description: string; target: string; allocations: string[]; titles: string[]; criteria: string[]; deadlines: string[]; evidenceRequirements: string[]; sources: string[]; evidencePolicyVersion: string; challengeBond: string; challengeWindow: string; }
const blankMilestone = { title: "", criteria: "", allocation: "", deadline: "", evidenceRequirement: "Public field report", sources: "1" };
const initial = { beneficiary: "", projectName: "", organization: "", projectReference: "", region: "", category: "", description: "", target: "", allocations: [""], titles: [""], criteria: [""], deadlines: [""], evidenceRequirements: ["Public field report"], sources: ["1"], evidencePolicyVersion: "v1", challengeBond: "", challengeWindow: "86400" } satisfies GrantPlanFields;
const positive = (value: string) => /^\d+$/.test(value) && BigInt(value) > 0n;
const deadline = (value: string) => { const result = Math.floor(new Date(`${value}T23:59:59Z`).getTime() / 1000); return Number.isFinite(result) ? result : 0; };

export function validateGrantPlan(fields: GrantPlanFields) {
  const errors: string[] = [];
  if (!isAddress(fields.beneficiary) || /^0x0{40}$/i.test(fields.beneficiary)) errors.push("A valid beneficiary address is required.");
  for (const [label, value, max] of [["Project name", fields.projectName, 120], ["Organization", fields.organization, 120], ["Project reference", fields.projectReference, 120], ["Region", fields.region, 120], ["Category", fields.category, 120], ["Description", fields.description, 1000]] as const) if (!value.trim() || value.length > max) errors.push(`${label} is required and must fit the contract limit.`);
  if (!positive(fields.target)) errors.push("Escrow target must be positive.");
  if (fields.titles.length < 1 || fields.titles.length > 5) errors.push("Choose one to five milestones.");
  const target = positive(fields.target) ? BigInt(fields.target) : 0n;
  const allocations = fields.allocations.map((value) => /^\d+$/.test(value) ? BigInt(value) : 0n);
  if (allocations.some((value) => value === 0n)) errors.push("Every milestone needs a positive allocation.");
  if (allocations.reduce((sum, value) => sum + value, 0n) !== target) errors.push(`Allocations must total ${fields.target || "the escrow target"} GEN.`);
  let previous = 0;
  fields.titles.forEach((title, index) => { if (!title.trim() || !fields.criteria[index]?.trim() || !fields.evidenceRequirements[index]?.trim()) errors.push(`Milestone ${index + 1} needs a title, criteria, and evidence requirement.`); const current = deadline(fields.deadlines[index]); if (current <= Math.floor(Date.now() / 1000) || current <= previous) errors.push("Milestone dates must be future and chronological."); previous = current; const count = Number(fields.sources[index]); if (!Number.isInteger(count) || count < 1 || count > 2) errors.push("Independent sources must be one or two per milestone."); });
  if (fields.evidencePolicyVersion !== "v1") errors.push("Evidence policy must be v1.");
  if (!positive(fields.challengeBond) || !positive(fields.challengeWindow)) errors.push("Challenge bond and window must be positive.");
  return { errors: [...new Set(errors)], canReview: errors.length === 0 };
}

function Field({ label, value, onChange, type = "text", placeholder }: { label: string; value: string; onChange(value: string): void; type?: string; placeholder?: string }) { return <label className="form-field"><span>{label}</span><input type={type} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} /></label>; }

export function GrantPlanWizard() {
  const [form, setForm] = useState<GrantPlanFields>(initial); const [step, setStep] = useState(0); const wallet = useWallet(); const transaction = useTransaction();
  const valid = useMemo(() => validateGrantPlan(form), [form]);
  const patch = (key: keyof GrantPlanFields, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const milestone = (index: number, key: "title" | "criteria" | "allocation" | "deadline" | "evidenceRequirement" | "sources", value: string) => setForm((current) => { const property = key === "title" ? "titles" : key === "allocation" ? "allocations" : key === "evidenceRequirement" ? "evidenceRequirements" : key === "sources" ? "sources" : key === "criteria" ? "criteria" : "deadlines"; const next = [...current[property]]; next[index] = value; return { ...current, [property]: next }; });
  const addMilestone = () => setForm((current) => current.titles.length === 5 ? current : ({ ...current, titles: [...current.titles, blankMilestone.title], criteria: [...current.criteria, blankMilestone.criteria], allocations: [...current.allocations, blankMilestone.allocation], deadlines: [...current.deadlines, blankMilestone.deadline], evidenceRequirements: [...current.evidenceRequirements, blankMilestone.evidenceRequirement], sources: [...current.sources, blankMilestone.sources] }));
  const sign = async () => { if (!valid.canReview || wallet.status !== "connected" || !wallet.account || !wallet.provider) return; const client = await createWriteClient(wallet.provider, wallet.account); const contract = createAidTrailContract({ address: process.env.NEXT_PUBLIC_AIDTRAIL_CONTRACT_ADDRESS, writeClient: client }); await transaction.execute(() => contract.createGrant({ beneficiary: form.beneficiary as Address, projectName: form.projectName, organization: form.organization, projectReference: form.projectReference, region: form.region, category: form.category, description: form.description, escrowTarget: BigInt(form.target), milestoneTitles: form.titles, milestoneCriteria: form.criteria, allocations: form.allocations.map(BigInt), deadlines: form.deadlines.map((item) => BigInt(deadline(item))), evidenceRequirements: form.evidenceRequirements, minIndependentSources: form.sources.map(BigInt), evidencePolicyVersion: form.evidencePolicyVersion, challengeBond: BigInt(form.challengeBond), challengeWindow: BigInt(form.challengeWindow), schemaVersion: 1n, readback: async () => true })); };
  return <section className="workflow-card grant-wizard"><p className="eyebrow">Sponsor plan</p><h1>Build a grant people can follow.</h1><p>Each promise is bound into the contract before funding opens.</p><ol className="wizard-steps">{["Identity", "Milestones", "Evidence", "Economics", "Review"].map((label, index) => <li className={index === step ? "is-current" : index < step ? "is-done" : ""} key={label}>{index + 1}. {label}</li>)}</ol>
    {step === 0 && <div className="form-grid"><Field label="Beneficiary wallet" value={form.beneficiary} placeholder="0x…" onChange={(value) => patch("beneficiary", value)} /><Field label="Project name" value={form.projectName} onChange={(value) => patch("projectName", value)} /><Field label="Organization" value={form.organization} onChange={(value) => patch("organization", value)} /><Field label="Public project reference" value={form.projectReference} placeholder="https://…" onChange={(value) => patch("projectReference", value)} /><Field label="Region" value={form.region} onChange={(value) => patch("region", value)} /><Field label="Category" value={form.category} onChange={(value) => patch("category", value)} /><label className="form-field form-field--wide"><span>Project description</span><textarea value={form.description} onChange={(event) => patch("description", event.target.value)} /></label></div>}
    {step === 1 && <div className="milestone-editor">{form.titles.map((_, index) => <fieldset key={index}><legend>Milestone {index + 1}</legend><div className="form-grid"><Field label="Title" value={form.titles[index]} onChange={(value) => milestone(index, "title", value)} /><Field label="Allocation (GEN)" type="number" value={form.allocations[index]} onChange={(value) => milestone(index, "allocation", value)} /><Field label="Deadline" type="date" value={form.deadlines[index]} onChange={(value) => milestone(index, "deadline", value)} /><Field label="Independent sources" type="number" value={form.sources[index]} onChange={(value) => milestone(index, "sources", value)} /><label className="form-field form-field--wide"><span>Criteria</span><textarea value={form.criteria[index]} onChange={(event) => milestone(index, "criteria", event.target.value)} /></label></div></fieldset>)}<button className="button button--quiet" type="button" onClick={addMilestone}>Add milestone</button></div>}
    {step === 2 && <div className="milestone-editor">{form.titles.map((_, index) => <Field key={index} label={`Milestone ${index + 1} evidence requirement`} value={form.evidenceRequirements[index]} onChange={(value) => milestone(index, "evidenceRequirement", value)} />)}<Field label="Evidence policy version" value={form.evidencePolicyVersion} onChange={(value) => patch("evidencePolicyVersion", value)} /></div>}
    {step === 3 && <div className="form-grid"><Field label="Escrow target (GEN)" type="number" value={form.target} onChange={(value) => patch("target", value)} /><Field label="Challenge bond (GEN)" type="number" value={form.challengeBond} onChange={(value) => patch("challengeBond", value)} /><Field label="Challenge window (seconds)" type="number" value={form.challengeWindow} onChange={(value) => patch("challengeWindow", value)} /></div>}
    {step === 4 && <div className="canonical-summary"><h2>Immutable contract summary</h2><p>The wallet signs this exact plan. Edits require returning to an earlier step before a transaction is submitted.</p><dl><dt>Beneficiary</dt><dd>{form.beneficiary || "—"}</dd><dt>Escrow target</dt><dd>{form.target || "0"} GEN</dd><dt>Milestones</dt><dd>{form.titles.map((title, index) => `${index + 1}. ${title || "Untitled"} — ${form.allocations[index] || "0"} GEN`).join(" · ")}</dd><dt>Evidence policy</dt><dd>{form.evidencePolicyVersion}; {form.challengeBond || "0"} GEN bond; {form.challengeWindow || "0"} sec window</dd></dl>{valid.errors.length > 0 && <ul className="form-errors">{valid.errors.map((error) => <li key={error}>{error}</li>)}</ul>}</div>}
    <div className="form-actions"><button type="button" className="button button--quiet" disabled={step === 0} onClick={() => setStep((current) => current - 1)}>Back</button>{step < 4 ? <button type="button" className="button" onClick={() => setStep((current) => current + 1)}>Continue</button> : <button type="button" className="button" disabled={!valid.canReview || wallet.status !== "connected"} onClick={() => void sign()}>Review and sign</button>}</div>{wallet.status !== "connected" && <p className="form-hint">Connect the sponsor wallet on Studionet to sign the complete plan.</p>}{transaction.state.phase !== "awaiting_wallet" && <TransactionStatus state={transaction.state} />}</section>;
}
